### ISSUE TITLE
enhance ip-detect help msg for user to write correct value

### ISSUE THREAD

**Issue by gongysh2004** [kubeclipper/kubeclipper#545]
**What's it about?**

For multiple nic environments,  ```kcctl deploy``` needs an argument to select which nic to use. but ```kcctl deploy --help``` does not give any hint on how to specify the wanted nic.  For my env, the ```kcctl deploy --ip-detect interface=eth1``` should be used.

Currently the help about ip-detect is:
root@compute1:~# kcctl deploy --help | grep ip-detect
      --ip-detect string                              Kc ip detect method. (default "first-found")

It should be better:
root@compute1:~# kcctl deploy --help | grep ip-detect
      --ip-detect string                              Kc ip detect method. (default "first-found",  interface=interface-name, or other possible value)

root@compute1:~# kcctl version
kcctl version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.1", GitCommit:"dc4100f97895df88b564baac5105b40f9b701d41", GitTreeState:"clean", BuildDate:"2022-12-12T08:44:29Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}

/kind feature-request

**Comment by simonyangcj** [comment]
Hi 大师兄， This is good suggestion,but it`s really hard to do because interface ip can be mismatch , say eth1 of node1 with ip address 10.0.0.20/24, eth1 of node200 with ip address 192.168.0.30/24 and this might end up with some node connectivity issues if there are not proper routed, I think we should use "can-reach" ip-detected method :)
